version: '3'

services:
  dwhexample-postgresql:
    build: build/postgresql
    image: dwhexample/postgresql
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - "./volumes/pgdata:/var/lib/postgresql/data"
      - "./volumes/data:/opt/data"
    tmpfs:
      - /run
      - /tmp
    ports:
      - "127.0.0.1:5432:5432"
    networks:
      - dwhexample

networks:
  dwhexample:
    external: true