name: 'crimes'
version: '0.1'
profile: 'crimes'
source-paths: [ "models" ]
analysis-paths: [ "analysis" ]
test-paths: [ "tests" ]
data-paths: [ "data" ]
macro-paths: [ "macros" ]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_modules"
  - "logs"

models:
  crimes:
    materialized: table
    staging:
      materialized: table
      tags: [ "staging", "hourly" ]
    marts:
      materialized: table
      tags: [ "marts", "hourly" ]

